const now = Date.now()
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString()
const daysFromNow = (n: number) => new Date(now + n * 86400000).toISOString()

export const campaigns = [
  { id: 'cmp-1', name: 'Ramadan Digital Campaign', description: 'Multi-platform campaign targeting UAE market during Ramadan', type: 'SOCIAL', platform: 'Instagram, Facebook', budget: 25000, actualSpend: 18500, currency: 'AED', startDate: daysAgo(30), endDate: daysAgo(0), status: 'COMPLETED', owner: { id: '4', name: 'Layla Mahmoud' }, leadsGenerated: 28, opportunitiesCreated: 4, revenueGenerated: 85000, createdAt: daysAgo(40) },
  { id: 'cmp-2', name: 'AI Solutions Launch', description: 'Campaign to promote new AI chatbot and automation services', type: 'CONTENT_MARKETING', platform: 'LinkedIn, Website', budget: 15000, actualSpend: 8200, currency: 'AED', startDate: daysAgo(15), endDate: daysFromNow(15), status: 'ACTIVE', owner: { id: '4', name: 'Layla Mahmoud' }, leadsGenerated: 12, opportunitiesCreated: 2, revenueGenerated: 0, createdAt: daysAgo(20) },
  { id: 'cmp-3', name: 'Google Ads - E-Commerce', description: 'Search ads targeting e-commerce development keywords in UAE', type: 'ADS', platform: 'Google Ads', budget: 10000, actualSpend: 6300, currency: 'AED', startDate: daysAgo(45), endDate: daysFromNow(15), status: 'ACTIVE', owner: { id: '5', name: 'Ahmed Noor' }, leadsGenerated: 18, opportunitiesCreated: 3, revenueGenerated: 45000, createdAt: daysAgo(50) },
  { id: 'cmp-4', name: 'Client Referral Program', description: 'Referral incentive program for existing clients', type: 'REFERRAL', platform: null, budget: 5000, actualSpend: 2000, currency: 'AED', startDate: daysAgo(60), endDate: daysFromNow(120), status: 'ACTIVE', owner: { id: '2', name: 'Sarah Al-Rashid' }, leadsGenerated: 5, opportunitiesCreated: 2, revenueGenerated: 55000, createdAt: daysAgo(65) },
  { id: 'cmp-5', name: 'Q2 Email Newsletter', description: 'Monthly newsletter with case studies and AI insights', type: 'EMAIL', platform: 'Email', budget: 2000, actualSpend: 0, currency: 'AED', startDate: daysFromNow(1), endDate: daysFromNow(90), status: 'DRAFT', owner: { id: '4', name: 'Layla Mahmoud' }, leadsGenerated: 0, opportunitiesCreated: 0, revenueGenerated: 0, createdAt: daysAgo(3) },
  { id: 'cmp-6', name: 'GITEX 2026 Presence', description: 'GITEX Technology Week booth and presentations', type: 'EVENT', platform: null, budget: 50000, actualSpend: 0, currency: 'AED', startDate: daysFromNow(180), endDate: daysFromNow(184), status: 'DRAFT', owner: { id: '1', name: 'Abdelrhman Elwakeel' }, leadsGenerated: 0, opportunitiesCreated: 0, revenueGenerated: 0, createdAt: daysAgo(10) },
]

export const socialAccounts = [
  { id: 'sa-1', client: { id: 'com-6', name: 'DAMAC' }, platform: 'INSTAGRAM', accountName: '@damacproperties', accountUrl: 'https://instagram.com/damacproperties', postingFrequency: '5x/week', isActive: true, createdAt: daysAgo(90) },
  { id: 'sa-2', client: { id: 'com-6', name: 'DAMAC' }, platform: 'FACEBOOK', accountName: 'DAMAC Properties', accountUrl: 'https://facebook.com/damacproperties', postingFrequency: '3x/week', isActive: true, createdAt: daysAgo(90) },
  { id: 'sa-3', client: { id: 'com-6', name: 'DAMAC' }, platform: 'LINKEDIN', accountName: 'DAMAC Properties', accountUrl: 'https://linkedin.com/company/damac', postingFrequency: '2x/week', isActive: true, createdAt: daysAgo(90) },
  { id: 'sa-4', client: { id: 'com-6', name: 'DAMAC' }, platform: 'TIKTOK', accountName: '@damacofficial', accountUrl: 'https://tiktok.com/@damacofficial', postingFrequency: '3x/week', isActive: true, createdAt: daysAgo(60) },
  { id: 'sa-5', client: { id: 'com-7', name: 'Arabian Adventures' }, platform: 'INSTAGRAM', accountName: '@arabianadventures', accountUrl: 'https://instagram.com/arabianadventures', postingFrequency: '4x/week', isActive: false, createdAt: daysAgo(120) },
]

export const contentItems = [
  { id: 'ci-1', socialAccount: { id: 'sa-1', platform: 'INSTAGRAM' }, client: 'DAMAC', platform: 'INSTAGRAM', contentType: 'REEL', plannedPublishDate: daysFromNow(1), caption: 'Luxury living redefined. Discover our latest waterfront residences. #DAMACLiving', approvalStatus: 'APPROVED', designer: { id: '5', name: 'Ahmed Noor' }, copywriter: { id: '4', name: 'Layla Mahmoud' }, createdAt: daysAgo(3) },
  { id: 'ci-2', socialAccount: { id: 'sa-1', platform: 'INSTAGRAM' }, client: 'DAMAC', platform: 'INSTAGRAM', contentType: 'CAROUSEL', plannedPublishDate: daysFromNow(3), caption: '5 Reasons to Invest in Dubai Real Estate in 2026', approvalStatus: 'CLIENT_REVIEW', designer: { id: '5', name: 'Ahmed Noor' }, copywriter: { id: '4', name: 'Layla Mahmoud' }, createdAt: daysAgo(2) },
  { id: 'ci-3', socialAccount: { id: 'sa-2', platform: 'FACEBOOK' }, client: 'DAMAC', platform: 'FACEBOOK', contentType: 'POST', plannedPublishDate: daysFromNow(2), caption: 'Virtual tour of our new project launch. Book your viewing today.', approvalStatus: 'DRAFT', designer: { id: '5', name: 'Ahmed Noor' }, copywriter: null, createdAt: daysAgo(1) },
  { id: 'ci-4', socialAccount: { id: 'sa-3', platform: 'LINKEDIN' }, client: 'DAMAC', platform: 'LINKEDIN', contentType: 'ARTICLE', plannedPublishDate: daysFromNow(5), caption: 'How AI is Transforming Property Management in the UAE', approvalStatus: 'INTERNAL_REVIEW', designer: null, copywriter: { id: '4', name: 'Layla Mahmoud' }, createdAt: daysAgo(1) },
  { id: 'ci-5', socialAccount: { id: 'sa-4', platform: 'TIKTOK' }, client: 'DAMAC', platform: 'TIKTOK', contentType: 'SHORT', plannedPublishDate: daysAgo(1), actualPublishDate: daysAgo(1), caption: 'POV: You just bought your dream home in Dubai 🏠', approvalStatus: 'PUBLISHED', designer: { id: '5', name: 'Ahmed Noor' }, copywriter: { id: '4', name: 'Layla Mahmoud' }, likes: 2400, comments: 85, shares: 120, reach: 45000, impressions: 62000, createdAt: daysAgo(5) },
  { id: 'ci-6', socialAccount: { id: 'sa-1', platform: 'INSTAGRAM' }, client: 'DAMAC', platform: 'INSTAGRAM', contentType: 'STORY', plannedPublishDate: daysAgo(0), caption: 'Behind the scenes - our latest photo shoot', approvalStatus: 'SCHEDULED', designer: { id: '5', name: 'Ahmed Noor' }, copywriter: null, createdAt: daysAgo(1) },
  { id: 'ci-7', socialAccount: { id: 'sa-2', platform: 'FACEBOOK' }, client: 'DAMAC', platform: 'FACEBOOK', contentType: 'VIDEO', plannedPublishDate: daysFromNow(7), caption: 'Project walkthrough video - needs client revisions on branding', approvalStatus: 'REVISION_NEEDED', designer: { id: '5', name: 'Ahmed Noor' }, copywriter: { id: '4', name: 'Layla Mahmoud' }, revisionNotes: 'Client requested different color grading and updated logo placement', createdAt: daysAgo(4) },
]
