export const companies = [
  { id: 'com-1', companyNumber: 'COM-0001', legalName: 'Al Futtaim Group', displayName: 'Al Futtaim', industry: 'Retail & Real Estate', country: 'UAE', city: 'Dubai', email: 'info@alfuttaim.ae', phone: '+97142345678', website: 'https://alfuttaim.com', lifecycleStage: 'CUSTOMER', healthScore: 85, employeeCount: 15000, annualRevenue: 5000000, accountOwner: { id: '2', name: 'Sarah Al-Rashid' }, contactCount: 2, dealCount: 1, createdAt: '2025-06-15' },
  { id: 'com-2', companyNumber: 'COM-0002', legalName: 'Dubai Holding LLC', displayName: 'Dubai Holding', industry: 'Conglomerate', country: 'UAE', city: 'Dubai', email: 'info@dubaiholding.ae', phone: '+97143456789', website: 'https://dubaiholding.com', lifecycleStage: 'CUSTOMER', healthScore: 92, employeeCount: 20000, annualRevenue: 10000000, accountOwner: { id: '2', name: 'Sarah Al-Rashid' }, contactCount: 2, dealCount: 1, createdAt: '2025-05-20' },
  { id: 'com-3', companyNumber: 'COM-0003', legalName: 'Noon Payments DMCC', displayName: 'Noon', industry: 'E-Commerce', country: 'UAE', city: 'Dubai', email: 'info@noon.com', phone: '+97144567890', website: 'https://noon.com', lifecycleStage: 'PROSPECT', healthScore: 60, employeeCount: 5000, annualRevenue: 2000000, accountOwner: { id: '4', name: 'Layla Mahmoud' }, contactCount: 1, dealCount: 1, createdAt: '2025-09-10' },
  { id: 'com-4', companyNumber: 'COM-0004', legalName: 'Careem Networks FZ-LLC', displayName: 'Careem', industry: 'Technology', country: 'UAE', city: 'Dubai', email: 'info@careem.com', phone: '+97145678901', website: 'https://careem.com', lifecycleStage: 'LEAD', healthScore: 40, employeeCount: 3000, annualRevenue: null, accountOwner: { id: '3', name: 'Omar Hassan' }, contactCount: 1, dealCount: 1, createdAt: '2025-11-01' },
  { id: 'com-5', companyNumber: 'COM-0005', legalName: 'Majid Al Futtaim Holding', displayName: 'MAF', industry: 'Retail & Entertainment', country: 'UAE', city: 'Dubai', email: 'info@maf.ae', phone: '+97146789012', website: 'https://majidalfuttaim.com', lifecycleStage: 'CUSTOMER', healthScore: 78, employeeCount: 40000, annualRevenue: 8000000, accountOwner: { id: '4', name: 'Layla Mahmoud' }, contactCount: 1, dealCount: 1, createdAt: '2025-04-01' },
  { id: 'com-6', companyNumber: 'COM-0006', legalName: 'DAMAC Properties PJSC', displayName: 'DAMAC', industry: 'Real Estate', country: 'UAE', city: 'Dubai', email: 'info@damac.ae', phone: '+97147890123', website: 'https://damacproperties.com', lifecycleStage: 'PROSPECT', healthScore: 55, employeeCount: 8000, annualRevenue: null, accountOwner: { id: '5', name: 'Ahmed Noor' }, contactCount: 1, dealCount: 1, createdAt: '2025-10-15' },
  { id: 'com-7', companyNumber: 'COM-0007', legalName: 'Arabian Adventures LLC', displayName: 'Arabian Adventures', industry: 'Tourism', country: 'UAE', city: 'Dubai', email: 'info@arabian.ae', phone: '+97148901234', website: 'https://arabian-adventures.com', lifecycleStage: 'CUSTOMER', healthScore: 70, employeeCount: 500, annualRevenue: 1500000, accountOwner: { id: '3', name: 'Omar Hassan' }, contactCount: 1, dealCount: 1, createdAt: '2025-03-10' },
  { id: 'com-8', companyNumber: 'COM-0008', legalName: 'STC Group', displayName: 'STC', industry: 'Telecommunications', country: 'KSA', city: 'Riyadh', email: 'info@stc.sa', phone: '+966112345678', website: 'https://stc.com.sa', lifecycleStage: 'LEAD', healthScore: 30, employeeCount: 22000, annualRevenue: null, accountOwner: { id: '2', name: 'Sarah Al-Rashid' }, contactCount: 1, dealCount: 1, createdAt: '2026-03-01' },
  { id: 'com-9', companyNumber: 'COM-0009', legalName: 'Kitopi DMCC', displayName: 'Kitopi', industry: 'FoodTech', country: 'UAE', city: 'Dubai', email: 'info@kitopi.com', phone: '+97149012345', website: 'https://kitopi.com', lifecycleStage: 'PROSPECT', healthScore: 50, employeeCount: 2000, annualRevenue: null, accountOwner: { id: '5', name: 'Ahmed Noor' }, contactCount: 1, dealCount: 1, createdAt: '2025-12-01' },
  { id: 'com-10', companyNumber: 'COM-0010', legalName: 'Property Finder FZ-LLC', displayName: 'Property Finder', industry: 'PropTech', country: 'UAE', city: 'Dubai', email: 'info@propertyfinder.ae', phone: '+97140123456', website: 'https://propertyfinder.ae', lifecycleStage: 'CUSTOMER', healthScore: 88, employeeCount: 600, annualRevenue: 3000000, accountOwner: { id: '4', name: 'Layla Mahmoud' }, contactCount: 1, dealCount: 1, createdAt: '2025-07-01' },
]
