const now = Date.now()
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString()
const daysFromNow = (n: number) => new Date(now + n * 86400000).toISOString()

export const quotations = [
  { id: 'quo-1', quotationNumber: 'QUO-0001', title: 'E-Commerce Platform Redesign', company: { id: 'com-1', name: 'Al Futtaim' }, contact: { id: 'con-1', name: 'Fatima Al-Sayegh' }, opportunity: { id: 'opp-1', title: 'E-Commerce Redesign' }, owner: { id: '2', name: 'Sarah Al-Rashid' }, issueDate: daysAgo(60), validUntil: daysAgo(30), subtotal: 85000, discountAmount: 0, taxAmount: 4250, totalAmount: 89250, currency: 'AED', status: 'ACCEPTED', version: 1, createdAt: daysAgo(60) },
  { id: 'quo-2', quotationNumber: 'QUO-0002', title: 'WhatsApp AI Chatbot Solution', company: { id: 'com-2', name: 'Dubai Holding' }, contact: { id: 'con-3', name: 'Khalid Bin Rashid' }, opportunity: { id: 'opp-2', title: 'AI Chatbot Implementation' }, owner: { id: '3', name: 'Omar Hassan' }, issueDate: daysAgo(45), validUntil: daysAgo(15), subtotal: 120000, discountAmount: 0, taxAmount: 6000, totalAmount: 126000, currency: 'AED', status: 'ACCEPTED', version: 2, createdAt: daysAgo(45) },
  { id: 'quo-3', quotationNumber: 'QUO-0003', title: 'SEO Optimization Package', company: { id: 'com-3', name: 'Noon' }, contact: { id: 'con-5', name: 'Aisha Khan' }, opportunity: { id: 'opp-3', title: 'SEO Package' }, owner: { id: '5', name: 'Ahmed Noor' }, issueDate: daysAgo(30), validUntil: daysFromNow(0), subtotal: 35000, discountAmount: 0, taxAmount: 1750, totalAmount: 36750, currency: 'AED', status: 'ACCEPTED', version: 1, createdAt: daysAgo(30) },
  { id: 'quo-4', quotationNumber: 'QUO-0004', title: 'Mobile App Development', company: { id: 'com-10', name: 'Property Finder' }, contact: { id: 'con-11', name: 'Sara Jaber' }, opportunity: { id: 'opp-10', title: 'Mobile App Development' }, owner: { id: '2', name: 'Sarah Al-Rashid' }, issueDate: daysAgo(20), validUntil: daysFromNow(10), subtotal: 150000, discountAmount: 5000, taxAmount: 7250, totalAmount: 152250, currency: 'AED', status: 'ACCEPTED', version: 1, createdAt: daysAgo(20) },
  { id: 'quo-5', quotationNumber: 'QUO-0005', title: 'CRM Integration Solution', company: { id: 'com-8', name: 'STC' }, contact: { id: 'con-9', name: 'Sultan Al-Ghamdi' }, opportunity: { id: 'opp-8', title: 'CRM Integration' }, owner: { id: '2', name: 'Sarah Al-Rashid' }, issueDate: daysAgo(5), validUntil: daysFromNow(25), subtotal: 200000, discountAmount: 10000, taxAmount: 9500, totalAmount: 199500, currency: 'AED', status: 'SENT', version: 1, createdAt: daysAgo(5) },
  { id: 'quo-6', quotationNumber: 'QUO-0006', title: 'Social Media Retainer Q2', company: { id: 'com-6', name: 'DAMAC' }, contact: { id: 'con-7', name: 'Hassan Malik' }, opportunity: null, owner: { id: '4', name: 'Layla Mahmoud' }, issueDate: daysAgo(2), validUntil: daysFromNow(14), subtotal: 36000, discountAmount: 0, taxAmount: 1800, totalAmount: 37800, currency: 'AED', status: 'DRAFT', version: 1, createdAt: daysAgo(2) },
]

export const proposals = [
  { id: 'prp-1', proposalNumber: 'PRP-0001', title: 'Al Futtaim Digital Transformation Proposal', company: { id: 'com-1', name: 'Al Futtaim' }, contact: { id: 'con-1', name: 'Fatima Al-Sayegh' }, opportunity: { id: 'opp-1', title: 'E-Commerce Redesign' }, issueDate: daysAgo(65), validUntil: daysAgo(35), subtotal: 85000, totalAmount: 89250, currency: 'AED', status: 'ACCEPTED', version: 1, createdAt: daysAgo(65) },
  { id: 'prp-2', proposalNumber: 'PRP-0002', title: 'AI-Powered Customer Support Solution', company: { id: 'com-2', name: 'Dubai Holding' }, contact: { id: 'con-3', name: 'Khalid Bin Rashid' }, opportunity: { id: 'opp-2', title: 'AI Chatbot Implementation' }, issueDate: daysAgo(50), validUntil: daysAgo(20), subtotal: 120000, totalAmount: 126000, currency: 'AED', status: 'ACCEPTED', version: 1, createdAt: daysAgo(50) },
  { id: 'prp-3', proposalNumber: 'PRP-0003', title: 'STC CRM Modernization Proposal', company: { id: 'com-8', name: 'STC' }, contact: { id: 'con-9', name: 'Sultan Al-Ghamdi' }, opportunity: { id: 'opp-8', title: 'CRM Integration' }, issueDate: daysAgo(3), validUntil: daysFromNow(27), subtotal: 200000, totalAmount: 199500, currency: 'AED', status: 'SENT', version: 1, createdAt: daysAgo(3) },
]

export const contracts = [
  { id: 'ctr-1', contractNumber: 'CTR-0001', title: 'E-Commerce Development Agreement', type: 'SERVICE', client: { id: 'com-1', name: 'Al Futtaim' }, contact: { id: 'con-1', name: 'Fatima Al-Sayegh' }, startDate: daysAgo(45), endDate: daysFromNow(15), value: 85000, currency: 'AED', status: 'ACTIVE', createdBy: { id: '2', name: 'Sarah Al-Rashid' }, signedAt: daysAgo(48), createdAt: daysAgo(50) },
  { id: 'ctr-2', contractNumber: 'CTR-0002', title: 'AI Chatbot Implementation Contract', type: 'SERVICE', client: { id: 'com-2', name: 'Dubai Holding' }, contact: { id: 'con-3', name: 'Khalid Bin Rashid' }, startDate: daysAgo(30), endDate: daysFromNow(30), value: 120000, currency: 'AED', status: 'ACTIVE', createdBy: { id: '3', name: 'Omar Hassan' }, signedAt: daysAgo(32), createdAt: daysAgo(35) },
  { id: 'ctr-3', contractNumber: 'CTR-0003', title: 'Social Media Management Retainer', type: 'RETAINER', client: { id: 'com-6', name: 'DAMAC' }, contact: { id: 'con-7', name: 'Hassan Malik' }, startDate: daysAgo(90), endDate: daysFromNow(90), renewalDate: daysFromNow(60), value: 72000, currency: 'AED', status: 'ACTIVE', createdBy: { id: '4', name: 'Layla Mahmoud' }, signedAt: daysAgo(92), createdAt: daysAgo(95) },
  { id: 'ctr-4', contractNumber: 'CTR-0004', title: 'Brand Identity NDA', type: 'NDA', client: { id: 'com-5', name: 'MAF' }, contact: { id: 'con-6', name: 'Rania Qasim' }, startDate: daysAgo(65), endDate: daysFromNow(300), value: null, currency: 'AED', status: 'ACTIVE', createdBy: { id: '4', name: 'Layla Mahmoud' }, signedAt: daysAgo(65), createdAt: daysAgo(67) },
  { id: 'ctr-5', contractNumber: 'CTR-0005', title: 'Mobile App Development Contract', type: 'SERVICE', client: { id: 'com-10', name: 'Property Finder' }, contact: { id: 'con-11', name: 'Sara Jaber' }, startDate: daysAgo(10), endDate: daysFromNow(80), value: 150000, currency: 'AED', status: 'ACTIVE', createdBy: { id: '2', name: 'Sarah Al-Rashid' }, signedAt: daysAgo(11), createdAt: daysAgo(14) },
]
