const now = Date.now()
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString()
const daysFromNow = (n: number) => new Date(now + n * 86400000).toISOString()

export const invoices = [
  { id: 'inv-1', invoiceNumber: 'INV-0001', client: { id: 'com-5', name: 'MAF' }, project: { id: 'prj-3', name: 'MAF Brand Identity Refresh' }, issueDate: daysAgo(10), dueDate: daysAgo(-20), subtotal: 45000, taxAmount: 2250, totalAmount: 47250, amountPaid: 47250, balanceDue: 0, currency: 'AED', status: 'PAID', createdBy: { id: '2', name: 'Sarah Al-Rashid' }, items: [{ description: 'Brand Identity Package', quantity: 1, unitPrice: 45000, totalPrice: 45000 }], createdAt: daysAgo(10) },
  { id: 'inv-2', invoiceNumber: 'INV-0002', client: { id: 'com-1', name: 'Al Futtaim' }, project: { id: 'prj-1', name: 'Al Futtaim E-Commerce Platform' }, issueDate: daysAgo(30), dueDate: daysAgo(0), subtotal: 42500, taxAmount: 2125, totalAmount: 44625, amountPaid: 44625, balanceDue: 0, currency: 'AED', status: 'PAID', createdBy: { id: '2', name: 'Sarah Al-Rashid' }, items: [{ description: 'E-Commerce Development - Phase 1', quantity: 1, unitPrice: 42500, totalPrice: 42500 }], createdAt: daysAgo(30) },
  { id: 'inv-3', invoiceNumber: 'INV-0003', client: { id: 'com-1', name: 'Al Futtaim' }, project: { id: 'prj-1', name: 'Al Futtaim E-Commerce Platform' }, issueDate: daysAgo(5), dueDate: daysFromNow(25), subtotal: 42500, taxAmount: 2125, totalAmount: 44625, amountPaid: 0, balanceDue: 44625, currency: 'AED', status: 'SENT', createdBy: { id: '2', name: 'Sarah Al-Rashid' }, items: [{ description: 'E-Commerce Development - Phase 2', quantity: 1, unitPrice: 42500, totalPrice: 42500 }], createdAt: daysAgo(5) },
  { id: 'inv-4', invoiceNumber: 'INV-0004', client: { id: 'com-2', name: 'Dubai Holding' }, project: { id: 'prj-2', name: 'Dubai Holding AI Chatbot' }, issueDate: daysAgo(20), dueDate: daysAgo(10), subtotal: 60000, taxAmount: 3000, totalAmount: 63000, amountPaid: 0, balanceDue: 63000, currency: 'AED', status: 'OVERDUE', createdBy: { id: '3', name: 'Omar Hassan' }, items: [{ description: 'AI Chatbot - Milestone 1', quantity: 1, unitPrice: 60000, totalPrice: 60000 }], createdAt: daysAgo(20) },
  { id: 'inv-5', invoiceNumber: 'INV-0005', client: { id: 'com-3', name: 'Noon' }, project: { id: 'prj-4', name: 'Noon SEO Optimization' }, issueDate: daysAgo(15), dueDate: daysFromNow(15), subtotal: 17500, taxAmount: 875, totalAmount: 18375, amountPaid: 18375, balanceDue: 0, currency: 'AED', status: 'PAID', createdBy: { id: '5', name: 'Ahmed Noor' }, items: [{ description: 'SEO Audit & Month 1', quantity: 1, unitPrice: 17500, totalPrice: 17500 }], createdAt: daysAgo(15) },
  { id: 'inv-6', invoiceNumber: 'INV-0006', client: { id: 'com-6', name: 'DAMAC' }, project: { id: 'prj-6', name: 'DAMAC Social Media Management' }, issueDate: daysAgo(3), dueDate: daysFromNow(27), subtotal: 12000, taxAmount: 600, totalAmount: 12600, amountPaid: 0, balanceDue: 12600, currency: 'AED', status: 'SENT', createdBy: { id: '4', name: 'Layla Mahmoud' }, items: [{ description: 'Social Media Management - Month 4', quantity: 1, unitPrice: 12000, totalPrice: 12000 }], createdAt: daysAgo(3) },
  { id: 'inv-7', invoiceNumber: 'INV-0007', client: { id: 'com-10', name: 'Property Finder' }, project: { id: 'prj-5', name: 'Property Finder Mobile App' }, issueDate: daysAgo(8), dueDate: daysFromNow(22), subtotal: 37500, taxAmount: 1875, totalAmount: 39375, amountPaid: 39375, balanceDue: 0, currency: 'AED', status: 'PAID', createdBy: { id: '2', name: 'Sarah Al-Rashid' }, items: [{ description: 'Mobile App - Discovery & Planning Phase', quantity: 1, unitPrice: 37500, totalPrice: 37500 }], createdAt: daysAgo(8) },
  { id: 'inv-8', invoiceNumber: 'INV-0008', client: { id: 'com-7', name: 'Arabian Adventures' }, project: { id: 'prj-7', name: 'Arabian Adventures Website' }, issueDate: daysAgo(2), dueDate: daysFromNow(28), subtotal: 16500, taxAmount: 825, totalAmount: 17325, amountPaid: 0, balanceDue: 17325, currency: 'AED', status: 'DRAFT', createdBy: { id: '3', name: 'Omar Hassan' }, items: [{ description: 'Website Discovery & Design - Deposit', quantity: 1, unitPrice: 16500, totalPrice: 16500 }], createdAt: daysAgo(2) },
  { id: 'inv-9', invoiceNumber: 'INV-0009', client: { id: 'com-6', name: 'DAMAC' }, project: { id: 'prj-6', name: 'DAMAC Social Media Management' }, issueDate: daysAgo(35), dueDate: daysAgo(5), subtotal: 12000, taxAmount: 600, totalAmount: 12600, amountPaid: 12600, balanceDue: 0, currency: 'AED', status: 'PAID', createdBy: { id: '4', name: 'Layla Mahmoud' }, items: [{ description: 'Social Media Management - Month 3', quantity: 1, unitPrice: 12000, totalPrice: 12000 }], createdAt: daysAgo(35) },
  { id: 'inv-10', invoiceNumber: 'INV-0010', client: { id: 'com-2', name: 'Dubai Holding' }, project: { id: 'prj-2', name: 'Dubai Holding AI Chatbot' }, issueDate: daysAgo(1), dueDate: daysFromNow(29), subtotal: 60000, taxAmount: 3000, totalAmount: 63000, amountPaid: 0, balanceDue: 63000, currency: 'AED', status: 'DRAFT', createdBy: { id: '3', name: 'Omar Hassan' }, items: [{ description: 'AI Chatbot - Milestone 2', quantity: 1, unitPrice: 60000, totalPrice: 60000 }], createdAt: daysAgo(1) },
]

export const payments = [
  { id: 'pay-1', paymentNumber: 'PAY-0001', invoice: { id: 'inv-1', invoiceNumber: 'INV-0001' }, client: { id: 'com-5', name: 'MAF' }, amount: 47250, currency: 'AED', paymentDate: daysAgo(5), paymentMethod: 'BANK_TRANSFER', reference: 'TRF-87654', createdAt: daysAgo(5) },
  { id: 'pay-2', paymentNumber: 'PAY-0002', invoice: { id: 'inv-2', invoiceNumber: 'INV-0002' }, client: { id: 'com-1', name: 'Al Futtaim' }, amount: 44625, currency: 'AED', paymentDate: daysAgo(12), paymentMethod: 'BANK_TRANSFER', reference: 'TRF-87655', createdAt: daysAgo(12) },
  { id: 'pay-3', paymentNumber: 'PAY-0003', invoice: { id: 'inv-5', invoiceNumber: 'INV-0005' }, client: { id: 'com-3', name: 'Noon' }, amount: 18375, currency: 'AED', paymentDate: daysAgo(8), paymentMethod: 'CREDIT_CARD', reference: 'CC-34521', createdAt: daysAgo(8) },
  { id: 'pay-4', paymentNumber: 'PAY-0004', invoice: { id: 'inv-7', invoiceNumber: 'INV-0007' }, client: { id: 'com-10', name: 'Property Finder' }, amount: 39375, currency: 'AED', paymentDate: daysAgo(3), paymentMethod: 'BANK_TRANSFER', reference: 'TRF-87660', createdAt: daysAgo(3) },
  { id: 'pay-5', paymentNumber: 'PAY-0005', invoice: { id: 'inv-9', invoiceNumber: 'INV-0009' }, client: { id: 'com-6', name: 'DAMAC' }, amount: 12600, currency: 'AED', paymentDate: daysAgo(2), paymentMethod: 'BANK_TRANSFER', reference: 'TRF-87665', createdAt: daysAgo(2) },
]
