const now = Date.now()
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString()

export const opportunityStages = [
  { id: 'os-1', name: 'Discovery', color: '#6366F1', probability: 10 },
  { id: 'os-2', name: 'Proposal', color: '#8B5CF6', probability: 30 },
  { id: 'os-3', name: 'Negotiation', color: '#3B82F6', probability: 60 },
  { id: 'os-4', name: 'Contract', color: '#06B6D4', probability: 80 },
  { id: 'os-5', name: 'Closed Won', color: '#22C55E', probability: 100 },
  { id: 'os-6', name: 'Closed Lost', color: '#EF4444', probability: 0 },
]

export const opportunities = [
  { id: 'opp-1', opportunityNumber: 'OPP-0001', title: 'Al Futtaim AI Chatbot', value: 25000, currency: 'AED', weightedValue: 17500, company: { id: 'com-1', name: 'Al Futtaim' }, contact: { id: 'con-1', name: 'Mohammed Al-Rashidi' }, stage: 'Negotiation', stageId: 'os-3', owner: { id: '2', name: 'Sarah Al-Rashid' }, expectedCloseDate: daysAgo(-15), probability: 70, service: 'AI Chatbot', createdAt: daysAgo(20) },
  { id: 'opp-2', opportunityNumber: 'OPP-0002', title: 'Dubai Holding Website Redesign', value: 45000, currency: 'AED', weightedValue: 38250, company: { id: 'com-2', name: 'Dubai Holding' }, contact: { id: 'con-2', name: 'Fatima Al-Zaabi' }, stage: 'Contract', stageId: 'os-4', owner: { id: '2', name: 'Sarah Al-Rashid' }, expectedCloseDate: daysAgo(-5), probability: 85, service: 'Corporate Website', createdAt: daysAgo(30) },
  { id: 'opp-3', opportunityNumber: 'OPP-0003', title: 'Noon CRM Automation', value: 18000, currency: 'AED', weightedValue: 3600, company: { id: 'com-3', name: 'Noon' }, contact: { id: 'con-3', name: 'Ali Kazmi' }, stage: 'Discovery', stageId: 'os-1', owner: { id: '3', name: 'Omar Hassan' }, expectedCloseDate: daysAgo(-30), probability: 20, service: 'CRM Automation', createdAt: daysAgo(10) },
  { id: 'opp-4', opportunityNumber: 'OPP-0004', title: 'MAF Social Media Management', value: 96000, currency: 'AED', weightedValue: 38400, company: { id: 'com-5', name: 'MAF' }, contact: { id: 'con-5', name: 'Khalid Bin Saeed' }, stage: 'Proposal', stageId: 'os-2', owner: { id: '4', name: 'Layla Mahmoud' }, expectedCloseDate: daysAgo(-20), probability: 40, service: 'Social Media Management', createdAt: daysAgo(15) },
  { id: 'opp-5', opportunityNumber: 'OPP-0005', title: 'Property Finder RAG Bot', value: 35000, currency: 'AED', weightedValue: 22750, company: { id: 'com-10', name: 'Property Finder' }, contact: { id: 'con-10', name: 'Aisha Al-Blooshi' }, stage: 'Negotiation', stageId: 'os-3', owner: { id: '2', name: 'Sarah Al-Rashid' }, expectedCloseDate: daysAgo(-10), probability: 65, service: 'RAG Knowledge Bot', createdAt: daysAgo(25) },
  { id: 'opp-6', opportunityNumber: 'OPP-0006', title: 'Arabian Adventures Brand Refresh', value: 12000, currency: 'AED', weightedValue: 12000, company: { id: 'com-7', name: 'Arabian Adventures' }, contact: { id: 'con-7', name: 'Rashid Al-Maktoum' }, stage: 'Closed Won', stageId: 'os-5', owner: { id: '3', name: 'Omar Hassan' }, expectedCloseDate: daysAgo(5), probability: 100, service: 'Brand Identity', createdAt: daysAgo(45), wonAt: daysAgo(5) },
  { id: 'opp-7', opportunityNumber: 'OPP-0007', title: 'STC Custom AI Platform', value: 120000, currency: 'AED', weightedValue: 18000, company: { id: 'com-8', name: 'STC' }, contact: { id: 'con-8', name: 'Sara Al-Otaibi' }, stage: 'Discovery', stageId: 'os-1', owner: { id: '2', name: 'Sarah Al-Rashid' }, expectedCloseDate: daysAgo(-60), probability: 15, service: 'Custom AI Solution', createdAt: daysAgo(5) },
  { id: 'opp-8', opportunityNumber: 'OPP-0008', title: 'DAMAC SEO & Ads', value: 84000, currency: 'AED', weightedValue: 29400, company: { id: 'com-6', name: 'DAMAC' }, contact: { id: 'con-6', name: 'Noura Al-Hashmi' }, stage: 'Proposal', stageId: 'os-2', owner: { id: '5', name: 'Ahmed Noor' }, expectedCloseDate: daysAgo(-25), probability: 35, service: 'SEO Optimization', createdAt: daysAgo(18) },
  { id: 'opp-9', opportunityNumber: 'OPP-0009', title: 'Careem WhatsApp Integration', value: 36000, currency: 'AED', weightedValue: 0, company: { id: 'com-4', name: 'Careem' }, contact: { id: 'con-4', name: 'Hind Al-Mansoori' }, stage: 'Closed Lost', stageId: 'os-6', owner: { id: '3', name: 'Omar Hassan' }, expectedCloseDate: daysAgo(2), probability: 0, service: 'WhatsApp Business API', createdAt: daysAgo(40), lostAt: daysAgo(2), lostReason: 'Went with competitor', lostCompetitor: 'Internal team' },
  { id: 'opp-10', opportunityNumber: 'OPP-0010', title: 'Kitopi Landing Pages', value: 9000, currency: 'AED', weightedValue: 8100, company: { id: 'com-9', name: 'Kitopi' }, contact: { id: 'con-9', name: 'Hassan Mirza' }, stage: 'Contract', stageId: 'os-4', owner: { id: '5', name: 'Ahmed Noor' }, expectedCloseDate: daysAgo(-3), probability: 90, service: 'Landing Page', createdAt: daysAgo(12) },
]
