const now = Date.now()
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString()
const daysFromNow = (n: number) => new Date(now + n * 86400000).toISOString()

export const tasks = [
  { id: 'tsk-1', taskNumber: 'TSK-0001', title: 'Set up Shopify Plus environment', description: 'Configure Shopify Plus store with custom theme', project: { id: 'prj-1', name: 'Al Futtaim E-Commerce Platform' }, assignedTo: { id: '3', name: 'Omar Hassan' }, priority: 'HIGH', status: 'COMPLETED', dueDate: daysAgo(30), completedAt: daysAgo(28), createdAt: daysAgo(45) },
  { id: 'tsk-2', taskNumber: 'TSK-0002', title: 'Design homepage wireframes', project: { id: 'prj-1', name: 'Al Futtaim E-Commerce Platform' }, assignedTo: { id: '5', name: 'Ahmed Noor' }, priority: 'HIGH', status: 'COMPLETED', dueDate: daysAgo(20), completedAt: daysAgo(18), createdAt: daysAgo(40) },
  { id: 'tsk-3', taskNumber: 'TSK-0003', title: 'Implement product catalog API', project: { id: 'prj-1', name: 'Al Futtaim E-Commerce Platform' }, assignedTo: { id: '3', name: 'Omar Hassan' }, priority: 'MEDIUM', status: 'IN_PROGRESS', dueDate: daysFromNow(3), createdAt: daysAgo(15) },
  { id: 'tsk-4', taskNumber: 'TSK-0004', title: 'Payment gateway integration', project: { id: 'prj-1', name: 'Al Futtaim E-Commerce Platform' }, assignedTo: { id: '3', name: 'Omar Hassan' }, priority: 'HIGH', status: 'TODO', dueDate: daysFromNow(10), createdAt: daysAgo(10) },
  { id: 'tsk-5', taskNumber: 'TSK-0005', title: 'Train NLP model on FAQ data', project: { id: 'prj-2', name: 'Dubai Holding AI Chatbot' }, assignedTo: { id: '4', name: 'Layla Mahmoud' }, priority: 'URGENT', status: 'IN_PROGRESS', dueDate: daysFromNow(5), createdAt: daysAgo(20) },
  { id: 'tsk-6', taskNumber: 'TSK-0006', title: 'Build WhatsApp webhook handler', project: { id: 'prj-2', name: 'Dubai Holding AI Chatbot' }, assignedTo: { id: '3', name: 'Omar Hassan' }, priority: 'HIGH', status: 'IN_REVIEW', dueDate: daysAgo(2), createdAt: daysAgo(15) },
  { id: 'tsk-7', taskNumber: 'TSK-0007', title: 'Design chatbot conversation flows', project: { id: 'prj-2', name: 'Dubai Holding AI Chatbot' }, assignedTo: { id: '4', name: 'Layla Mahmoud' }, priority: 'MEDIUM', status: 'COMPLETED', dueDate: daysAgo(10), completedAt: daysAgo(8), createdAt: daysAgo(25) },
  { id: 'tsk-8', taskNumber: 'TSK-0008', title: 'Run technical SEO audit', project: { id: 'prj-4', name: 'Noon SEO Optimization' }, assignedTo: { id: '5', name: 'Ahmed Noor' }, priority: 'HIGH', status: 'COMPLETED', dueDate: daysAgo(10), completedAt: daysAgo(9), createdAt: daysAgo(20) },
  { id: 'tsk-9', taskNumber: 'TSK-0009', title: 'Fix meta tags and schema markup', project: { id: 'prj-4', name: 'Noon SEO Optimization' }, assignedTo: { id: '5', name: 'Ahmed Noor' }, priority: 'MEDIUM', status: 'IN_PROGRESS', dueDate: daysFromNow(7), createdAt: daysAgo(8) },
  { id: 'tsk-10', taskNumber: 'TSK-0010', title: 'Create UX research plan', project: { id: 'prj-5', name: 'Property Finder Mobile App' }, assignedTo: { id: '4', name: 'Layla Mahmoud' }, priority: 'HIGH', status: 'IN_PROGRESS', dueDate: daysFromNow(5), createdAt: daysAgo(10) },
  { id: 'tsk-11', taskNumber: 'TSK-0011', title: 'Create social content calendar for April', project: { id: 'prj-6', name: 'DAMAC Social Media Management' }, assignedTo: { id: '5', name: 'Ahmed Noor' }, priority: 'URGENT', status: 'TODO', dueDate: daysFromNow(2), createdAt: daysAgo(5) },
  { id: 'tsk-12', taskNumber: 'TSK-0012', title: 'Design brand mood boards', project: { id: 'prj-7', name: 'Arabian Adventures Website' }, assignedTo: { id: '5', name: 'Ahmed Noor' }, priority: 'MEDIUM', status: 'TODO', dueDate: daysFromNow(3), createdAt: daysAgo(5) },
  { id: 'tsk-13', taskNumber: 'TSK-0013', title: 'Follow up with STC on requirements doc', project: { id: 'prj-8', name: 'STC CRM Integration' }, assignedTo: { id: '2', name: 'Sarah Al-Rashid' }, priority: 'HIGH', status: 'TODO', dueDate: daysFromNow(1), createdAt: daysAgo(3) },
  { id: 'tsk-14', taskNumber: 'TSK-0014', title: 'Review competitor social strategy', description: 'Analyze top 5 competitor Instagram accounts', project: null, assignedTo: { id: '4', name: 'Layla Mahmoud' }, priority: 'LOW', status: 'TODO', dueDate: daysFromNow(14), createdAt: daysAgo(2) },
  { id: 'tsk-15', taskNumber: 'TSK-0015', title: 'Prepare monthly client reports', project: null, assignedTo: { id: '2', name: 'Sarah Al-Rashid' }, priority: 'MEDIUM', status: 'BLOCKED', dueDate: daysFromNow(3), createdAt: daysAgo(1) },
]
