const now = Date.now()
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString()
const daysFromNow = (n: number) => new Date(now + n * 86400000).toISOString()

export const tickets = [
  { id: 'tkt-1', ticketNumber: 'TKT-0001', subject: 'Product images not loading on mobile', description: 'Several product images return 404 on Safari mobile browsers', client: { id: 'com-1', name: 'Al Futtaim' }, project: { id: 'prj-1', name: 'Al Futtaim E-Commerce Platform' }, type: 'BUG', priority: 'HIGH', assignedTo: { id: '3', name: 'Omar Hassan' }, status: 'IN_PROGRESS', slaDueAt: daysFromNow(1), createdBy: { id: '2', name: 'Sarah Al-Rashid' }, createdAt: daysAgo(2) },
  { id: 'tkt-2', ticketNumber: 'TKT-0002', subject: 'Chatbot response time exceeds 5s', description: 'AI responses taking over 5 seconds during peak hours', client: { id: 'com-2', name: 'Dubai Holding' }, project: { id: 'prj-2', name: 'Dubai Holding AI Chatbot' }, type: 'BUG', priority: 'URGENT', assignedTo: { id: '4', name: 'Layla Mahmoud' }, status: 'OPEN', slaDueAt: daysFromNow(0), createdBy: { id: '3', name: 'Omar Hassan' }, createdAt: daysAgo(1) },
  { id: 'tkt-3', ticketNumber: 'TKT-0003', subject: 'Add Arabic language support to chatbot', description: 'Client requested full Arabic language support for the AI chatbot', client: { id: 'com-2', name: 'Dubai Holding' }, project: { id: 'prj-2', name: 'Dubai Holding AI Chatbot' }, type: 'FEATURE_REQUEST', priority: 'MEDIUM', assignedTo: { id: '4', name: 'Layla Mahmoud' }, status: 'NEW', slaDueAt: daysFromNow(7), createdBy: { id: '3', name: 'Omar Hassan' }, createdAt: daysAgo(3) },
  { id: 'tkt-4', ticketNumber: 'TKT-0004', subject: 'SEO report clarification needed', description: 'Client needs clarification on backlink quality metrics in monthly report', client: { id: 'com-3', name: 'Noon' }, project: { id: 'prj-4', name: 'Noon SEO Optimization' }, type: 'QUESTION', priority: 'LOW', assignedTo: { id: '5', name: 'Ahmed Noor' }, status: 'RESOLVED', resolvedAt: daysAgo(1), createdBy: { id: '5', name: 'Ahmed Noor' }, createdAt: daysAgo(5) },
  { id: 'tkt-5', ticketNumber: 'TKT-0005', subject: 'Instagram reel not published on schedule', description: 'Scheduled reel for April 3 was not published - scheduling tool error', client: { id: 'com-6', name: 'DAMAC' }, project: { id: 'prj-6', name: 'DAMAC Social Media Management' }, type: 'SUPPORT', priority: 'HIGH', assignedTo: { id: '4', name: 'Layla Mahmoud' }, status: 'RESOLVED', resolvedAt: daysAgo(2), createdBy: { id: '4', name: 'Layla Mahmoud' }, createdAt: daysAgo(4) },
  { id: 'tkt-6', ticketNumber: 'TKT-0006', subject: 'Update brand colors in style guide', description: 'MAF requested minor color adjustment to the brand guide secondary palette', client: { id: 'com-5', name: 'MAF' }, project: { id: 'prj-3', name: 'MAF Brand Identity Refresh' }, type: 'CHANGE_REQUEST', priority: 'LOW', assignedTo: { id: '5', name: 'Ahmed Noor' }, status: 'CLOSED', resolvedAt: daysAgo(8), closedAt: daysAgo(7), createdBy: { id: '4', name: 'Layla Mahmoud' }, createdAt: daysAgo(12) },
  { id: 'tkt-7', ticketNumber: 'TKT-0007', subject: 'Mobile app onboarding flow feedback', description: 'Client shared feedback on the onboarding flow wireframes, needs revision', client: { id: 'com-10', name: 'Property Finder' }, project: { id: 'prj-5', name: 'Property Finder Mobile App' }, type: 'CHANGE_REQUEST', priority: 'MEDIUM', assignedTo: { id: '4', name: 'Layla Mahmoud' }, status: 'WAITING_CLIENT', createdBy: { id: '2', name: 'Sarah Al-Rashid' }, createdAt: daysAgo(3) },
  { id: 'tkt-8', ticketNumber: 'TKT-0008', subject: 'SSL certificate expiring soon', description: 'SSL certificate for staging environment expires in 10 days', client: null, project: { id: 'prj-1', name: 'Al Futtaim E-Commerce Platform' }, type: 'SUPPORT', priority: 'HIGH', assignedTo: { id: '3', name: 'Omar Hassan' }, status: 'NEW', slaDueAt: daysFromNow(3), createdBy: { id: '3', name: 'Omar Hassan' }, createdAt: daysAgo(1) },
]
